export const ThreadsColumns = () => [
  {
    field: "created_at",
    headerName: "Time",
    flex: 1,
    minWidth: 150,
    editable: false,
  },
  {
    field: "bot_name",
    headerName: "Bot Name",
    flex: 1,
    minWidth: 100,
    editable: false,
  },
  {
    field: "thread_id",
    headerName: "Thread ID",
    flex: 1,
    minWidth: 100,
    editable: false,
    sortable: false,
  },
  {
    field: "user_message",
    headerName: "User message",
    flex: 1,
    minWidth: 150,
    editable: false,
  },
  {
    field: "bot_message",
    headerName: "Bot Message",
    flex: 1,
    minWidth: 150,
    editable: false,
  },
  {
    field: "user_email",
    headerName: "Callback",
    flex: 1,
    minWidth: 150,
    editable: false,
  },
]
